"""empty message

Revision ID: 19c2d985d08e
Revises: c2dd9410a475
Create Date: 2020-04-14 20:40:32.458002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c2d985d08e'
down_revision = 'c2dd9410a475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('image_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'image_link')
    # ### end Alembic commands ###
