"""empty message

Revision ID: f42a9735d245
Revises: d7a1be17811a
Create Date: 2020-04-14 20:18:24.139951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42a9735d245'
down_revision = 'd7a1be17811a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('customers', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
